name: Test
on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      python-version:
        required: true
        type: string
      poetry-version:
        required: true
        type: string
jobs:
  quality:
    runs-on: ${{ inputs.os }}
    name: Test (${{ inputs.os }}, python${{ inputs.python-version }})
    steps:
      - name: Synchronize repository
        uses: actions/checkout@v4
      - name: Setup Python ${{ inputs.python-version }} with Poetry ${{ inputs.poetry-version }}
        uses: ./.github/actions/setup-env
        with:
          python-version: ${{ inputs.python-version }}
          poetry-version: ${{ inputs.poetry-version }}
      - name: Run tests
        run: poetry run python -m pytest --cov=src/trackotron tests
